[fabric]
username = "Admin"
ccid = "broker"
channel_id = "mychannel"
org = "org2"
timeout_height = 30
chain_id = "3"
dynamic_validators = false

[[services]]
id = "mychannel&transfer"
name = "transfer"

[[services]]
id = "mychannel&data_swapper"
name = "data_swapper"