title = "Mock"

[appchain]
bxh_id = "1356"
appchain_id = "testchain"
port = "8081"

[mode]
type = "relay" # relay or direct
[mode.relay]
timeout_height = 50

[mode.direct]
chainId = "chain0"
serviceId = "0x6DCB3337cd4Ec41d88E62A96123bF3a4E06A7e13"
timeout_period = 60
