name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Run golanci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: Mushus/golangci-linter@v1

      - name: Go report card
        uses: creekorful/goreportcard-action@v1.0


#  test:
#    name: Run unittest
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up Go
#        uses: actions/setup-go@v1
#        with:
#          go-version: 1.13
#
#      - name: Check out code
#        uses: actions/checkout@v1
#
#      - name: Run Unit tests.
#        run: |
#          git clone https://github.com/meshplus/pier.git ../pier
#          export PATH=$PATH:$(go env GOPATH)/bin
#          make prepare
#          make test-coverage
#
#          #      - name: Upload Coverage report to CodeCov
#          # uses: codecov/codecov-action@v1.0.0
#          # with:
#          # token: ${{secrets.CODECOV_TOKEN}}
#          #file: ./coverage.txt

  build:
    name: Build project
    runs-on: ubuntu-latest
#    needs: [lint, test]
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Go build
        run: |
          git clone https://github.com/meshplus/pier.git ../pier
          go build -v --buildmode=plugin ./*.go
