name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Build Release on Linux and Macos
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build Binary
        run: make release-binary

      - name: Release Binary
        uses: softprops/action-gh-release@v1
        with:
          files: build/fabric-client-v*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}